name: Publish

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:
    if: github.repository == 'manga-py/manga-py' && startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install build
      - name: Build setup
        run: python prepare_setup.py
      - name: Build package
        run: python -m build
      - name: Publish package
        uses: google-github-actions/release-please-action@c078ea33917ab8cfa5300e48f4b7e6b16606aede # google-github-actions/release-please-action@v3.7.8
        with:
          release-type: python
          token: 'pypi-AgEIcHlwaS5vcmcCJDkyMjNjOGNlLWNiNGEtNGY5NC1hNzNlLTAwMTMyMWFkZGZkMAACEFsxLFsibWFuZ2EtcHkiXV0AAixbMixbIjFmZGZkNmViLTk3ZDktNDc1YS1iYjYzLTMzNTk2MjA4MzhlMCJdXQAABiCwq9Vi5e6fJHQK1X86LCQsBAI7JJ0dWuWZFt8WK3OJQA'
